### ISSUE TITLE
Maven index source becomes unstable and collapses after some time

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-crawler#27]
**Describe the bug**
After some time the discovery stream collapses as no more identifiers can be read from the source. There seems to be an issue with HTTP connection reading from the maven index. It may be timing out. 
The stack trace reads like this:
```
[2018-10-19 11:24:31,703]  d.u.c.s.d.c.s.ElasticActor - Stream failed!,
java.lang.RuntimeException: read error,
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.nextRecord(ChunkReader.java:155),
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.next(ChunkReader.java:138),
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.next(ChunkReader.java:112),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.IndexProcessing$MavenIndexReader.read(IndexProcessing.scala:66),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.IndexProcessing.$anonfun$createSource$3(IndexProcessing.scala:39),
	at akka.stream.impl.UnfoldResourceSource$$anon$1.onPull(UnfoldResourceSource.scala:42),
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526),
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:422),
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588),
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45),
Caused by: java.net.SocketException: Connection reset,
	at java.net.SocketInputStream.read(SocketInputStream.java:210),
	at java.net.SocketInputStream.read(SocketInputStream.java:141),
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284),
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345),
	at sun.net.www.MeteredStream.read(MeteredStream.java:134),
	at java.io.FilterInputStream.read(FilterInputStream.java:133),
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393),
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246),
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286),
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345),
[2018-10-19 11:24:31,709]  d.u.c.s.d.c.s.ElasticActor - Stream failed!,
java.lang.RuntimeException: read error,
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.nextRecord(ChunkReader.java:155),
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.next(ChunkReader.java:138),
	at org.apache.maven.index.reader.ChunkReader$IndexIterator.next(ChunkReader.java:112),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.IndexProcessing$MavenIndexReader.read(IndexProcessing.scala:66),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.IndexProcessing.$anonfun$createSource$3(IndexProcessing.scala:39),
	at akka.stream.impl.UnfoldResourceSource$$anon$1.onPull(UnfoldResourceSource.scala:42),
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526),
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:422),
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588),
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45),
Caused by: java.net.SocketException: Connection reset,
	at java.net.SocketInputStream.read(SocketInputStream.java:210),
	at java.net.SocketInputStream.read(SocketInputStream.java:141),
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284),
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345),
	at sun.net.www.MeteredStream.read(MeteredStream.java:134),
	at java.io.FilterInputStream.read(FilterInputStream.java:133),
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393),
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246),
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286),
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345),
```

**To Reproduce**
Run a crawler instance with a discovery process for some time. The bug will eventually occur and processing will cease.

**Expected behavior**
The stream source should be stable not to crash the stream.

**Screenshots**
n/a

**Affected components (if known)**
crawler

**Desktop (please complete the following information, if relevant):**
n/r

**Smartphone (please complete the following information, if relevant):**
n/r

**Additional context**
A few ideas already sprung to my find:
* gracefully end the source after a problem and restart the process
* check the timeouts attached to the connection
* first create a local copy of the index and then read locally
* index from a local proxy where timeouts can be configured
* implement a totally different `Source` using directory traversal

**Comment by bhermann** [comment]
Uhhh just learning that there are backoff operators and kill switches already in akka streams... Neat!
https://doc.akka.io/docs/akka/2.5/stream/stream-error.html

**Comment by bhermann** [comment]
Driving the read timeout incredibly high has apparently helped a lot. 
The backoff handler seems be a good idea nonetheless.
