### ISSUE TITLE
Encoding failure when constructing maven URLs

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-crawler#28]
**Describe the bug**
In some cases parts of maven URLs contains characters that need to be escaped. When URLs are being constructed this crashes the stream. 

**To Reproduce**
See following stack trace for example: 
```

[2018-10-22 14:59:15,404]  d.u.c.s.d.c.s.ElasticActor - Pushing new maven identifier to elastic: [net.java.dev.jogl:jogl:${parent.version}],
	at akka.actor.Actor.aroundReceive(Actor.scala:517),
	at akka.actor.Actor.aroundReceive$(Actor.scala:515),
[2018-10-22 14:59:15,405]  d.u.c.s.d.c.s.ElasticActor - Pushing Hermes results for net.java.dev.laf-plugin:laf-plugin:0.2 under id http://repo1.maven.org/maven2/:net.java.dev.laf-plugin:laf-plugin:0.2.,
[2018-10-22 14:59:15,411]  a.a.OneForOneStrategy - Illegal character in path at index 1: ${parent.version}/,
java.lang.IllegalArgumentException: Illegal character in path at index 1: ${parent.version}/,
	at java.net.URI.create(URI.java:852),
	at java.net.URI.resolve(URI.java:1036),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.MavenIdentifier.constructArtifactBaseUri(MavenIdentifier.scala:42),
	at de.upb.cs.swt.delphi.crawler.discovery.maven.MavenIdentifier.toJarLocation(MavenIdentifier.scala:31),
	at de.upb.cs.swt.delphi.crawler.preprocessing.MavenDownloadActor$$anonfun$receive$1.applyOrElse(MavenDownloadActor.scala:32),
	at de.upb.cs.swt.delphi.crawler.preprocessing.MavenDownloadActor.aroundReceive(MavenDownloadActor.scala:25),
	at akka.actor.ActorCell.invoke(ActorCell.scala:557),
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588),
Caused by: java.net.URISyntaxException: Illegal character in path at index 1: ${parent.version}/,
	at java.net.URI$Parser.checkChars(URI.java:3021),
	at java.net.URI$Parser.fail(URI.java:2848),
	at java.net.URI$Parser.parseHierarchical(URI.java:3105),
	at java.net.URI$Parser.parse(URI.java:3063),
	at java.net.URI.<init>(URI.java:588),
	at java.net.URI.create(URI.java:850)
```
**Expected behavior**
URL parts are properly encoded and result to the appropriate artifact.
Stream configuration is robust enough to tolerate these errors.

**Screenshots**
n/a

**Affected components (if known)**
crawler

**Desktop (please complete the following information, if relevant):**
n/r

**Smartphone (please complete the following information, if relevant):**
n/r

**Additional context**
none

**Comment by bhermann** [comment]
Closed with fdb8c6d
